renamed script and have it use PLEXIL_PLAN_DIR to find output directory

diff --git a/ow_plexil/scripts/ow-compile-plan b/ow_plexil/scripts/ow-compile-plan
--- a/ow_plexil/scripts/ow-compile-plan
+++ b/ow_plexil/scripts/ow-compile-plan
@@ -1,7 +1,5 @@
 #!/bin/bash
 
-# plexilcow (PLEXIL Compiler for OceanWATERS).
-
 # Simple script for compiling a single PLEXIL plan (.plp file).
 # Compiled version (.plx) is placed in the current deployment
 # directory.  Assumes that the PLEXIL compiler (plexilc) is in the
@@ -12,8 +10,17 @@ if [ $# -ne 1 ]; then
     exit 1
 fi
 
+if [ -z "$PLEXIL_PLAN_DIR" ]
+then
+    echo 'Error: environment PLEXIL_PLAN_DIR is not defined, '
+    echo 'which suggests that your workspace is not set up. '
+    echo 'See that your workspace is built and that your '
+    echo 'devel/setup.bash file is sourced.'
+    exit 1
+fi
+
 input_file="$1"
-output_directory="$HOME/ow/devel/.private/ow_plexil/etc/plexil/"
+output_directory="$PLEXIL_PLAN_DIR/../../.private/ow_plexil/etc/plexil/"
 
 if [ ! -f "${input_file}" ]; then
     echo "Input file '${input_file}' not found."
@@ -23,5 +30,4 @@ fi
 base_filename=$(basename "$input_file" .plp)
 
 # The '-p' option formats the output XML.
-
 plexilc -p -o "${output_directory}${base_filename}.plx" "${input_file}"
